### ISSUE TITLE
Multiplayer game should only be available if user is online

### ISSUE THREAD

**Issue by adnanusman** [ignacioxd/ragin-mages#33]
Need to determine if user is online or offline, which will decide whether multiplayer option is available to user or not.

**Comment by scottwestover** [comment]
Instead of using `navigator.onLine`, the next enhancement should:

Overhaul of the WebSocket functionality to fulfill the following requirements:

- The connection is established on the TitleScreen or earlier and is maintained throughout the lifetime of the game.
- Take advantage of the rooms and namespaces functionality of socket.io so that there are namespaces for different "game arenas" to limit the number of people in a single game arena, and to have a room for the lobby area and a room for the game (arena) so that events are sent only to those clients who need to receive them.

**Comment by ignacioxd** [comment]
This was addressed in 57ba70175c99d612e9860fce4e342125363f23e6
