### ISSUE TITLE
Sprite face direction we fire projectile

### ISSUE THREAD

**Issue by levyadams** [ignacioxd/ragin-mages#42]
If that is the behavior we end up wanting, we could just make points outside of the player character's x and y location and draw a vector from each to see which is closest to the mouse, and animate the character from there, returning to its previous animation direction after firing.

Any thoughts?

**Comment by ignacioxd** [comment]
That's a good idea to consider. At some point someone mentioned they would want to be able to move in one direction but shoot in any other arbitrary direction like you can do in most shooters. I'm open to trying multiple approaches, but here are some thoughts:

1. Character sprites only have 8 directions, but we can shoot in 360 degrees. The idea of choosing the closest animation based on shot direction sounds promising. We can try to see how it feels.
2. Shots are fired fast relative to movement and animation speed. Maybe characters cannot move while firing. Otherwise, it would look weird to move in a different direction than what the character is facing at. This might be a nice mechanic to add. Then, you can only fire once the previous firing animation has stopped.
