### ISSUE TITLE
Configure Client and Server to use config files

### ISSUE THREAD

**Issue by AtlantaDancer** [ignacioxd/ragin-mages#55]
For ease of development/testing and then deployment the use of config files would be convenient.  This allows us to have a DEV config file pointing to localhost and a production config that can point to the deployment IP address. 

I currently have a version on my computer that uses config files to generate the static files for DEV or PRODUCTION.  I can do a pull request hopefully tomorrow with that code.  I will look to adapt that code to use https://github.com/henrikjoreteg/getconfig or something like it to dynamically read the a config JSON file with the socket IO port.

**Comment by ignacioxd** [comment]
This is a great idea, thanks!

Given that Phaser supports loading JSON files natively, rather than adding an additional dependency, it may be better to simply load this config in the loading screen, as part of the asset loading process. 

That particular repository you linked seems to be for NodeJS projects, so I'm not sure it will work for the game portion of the project without modification.
