### ISSUE TITLE
Add credits, controls, and settings DOMmodal

### ISSUE THREAD

**Issue by PepperAddict** [ignacioxd/ragin-mages#73]
I'm going to assume it's a lot like the title page? 

I'll work on this tomorrow (Tuesday).

Comment here if there's something I should know. Or on slack...

**Comment by ignacioxd** [comment]
I'd start with the credits screen first. Maybe it should be implemented using the new `DOMModal`, instead of a whole Phaser scene. What do you think?

What do you have in mind for controls?

**Comment by PepperAddict** [comment]
I think that's a great idea. I was actually wondering how it would be done on the same scene and completely forgot we already have something like that. Hmmm...  I'll use the Modal we currently have as reference. :)

**Comment by levyadams** [comment]
Hows work with the Modal going? I wanted to add another button to one of those screens to send the user back to the start screen.

**Comment by PepperAddict** [comment]
Sorry @levyadams ! I should really push what I have now that way you can put your addition.

**Comment by PepperAddict** [comment]
![idea2](https://user-images.githubusercontent.com/4171505/38164495-a0ec9874-34d3-11e8-9d6a-98291e44f4e4.png)
lol sorry, my handwriting is awful. 

Here's my idea for the setting's page. The bottom part may be way too advanced for me though D:

**Comment by adnanusman** [comment]
I can help with that part @pepper.

**Comment by PepperAddict** [comment]
Thank you @adnanusman ! Is there a way we can collaborate with each other on this? Should we create a branch to work on this? I'm still new to github. 
I can just push a bare bone setting's page with buttons that doesn't do anything for right now if this template is okay.

**Comment by adnanusman** [comment]
I think that works best, let's just create a separate branch and work on this. Looks good to me. Maybe click instead of m1? Thoughts, anyone else?

**Comment by PepperAddict** [comment]
I forgot to add zoom in and out for the controls. I may need to redo that sketch lol. eh i'll just edit in there. 
I agree M1 may be too vague. Actually most of the words need to be reworked. Let me know what we come up with. I'll just get started and change the text later.

**Comment by ignacioxd** [comment]
I have a question about this screen. Is the idea to be able to customize these controls, or just show players how to use it? Right now we don't really have a way to change key/mouse bindings, but we can look into adding that option if you think it's useful. I think the bottom part controls are really the only settings we can offer right now.

Instead of "M1", I'd say "Left Click". I'd also split up the "Clear Data" button into "Clear Cache" and "Reset Settings" buttons.

I'm not sure if the player name should be a setting on this screen or if the name should be specified as part of the character selection screen. I was thinking that some players might want to change their player name often as they join or rejoin the game, so bringing that closer to the game may make that easier for them.

Now that I'm thinking about the handle and the character selection screen, I wonder if some players would just find it tedious to have to select a character every time they want to play. Maybe another setting we can have is the option for the player to select a character to bypass the character selection screen. So the options we could have here are something like: "Choose every time", "Random character", and each of the characters we have. I guess it would make sense to put the player name setting on this page in this case.

Just random thoughts.

**Comment by adnanusman** [comment]
@PepperAddict from what I understand I think he's saying that there will be an option to choose a default character instead of having to choose one every time. If the player selects a character and ticks a box that says 'make default' or if the player wants to randomize this they can check the box 'random', then they won't have to choose the character at all and the game chooses the character for the player.

These settings can be changed in the settings maybe? Maybe by adding a 'Remove default character' option, and possibly an 'undo character ramdomizer'.

**Comment by ignacioxd** [comment]
Maybe we need another button for "How to Play" or just a "?" in the corner. I agree that showing control instructions somewhere in the game is late. I just worry that people would not find the instructions for how to use the game in a menu called settings, unless they expect to be able to change the controls.

During the game, other than moving, I think the following controls should be possible: +/- for zooming, ESC to allow the player to quit the game (maybe with a confirmation dialog), and Q or any other key to toggle the leaderboard. That may be enough for now. We may add more things as we add features to the game.

For the last part, @adnanusman is mostly correct. I was thinking we could have a dropdown menu labeled "Always play as:" on the settings page with options like:
* Choose every time
* Random
* Mage
* Knight
* ... etc

The character selection screen will only be shown if "Choose every time" is the current setting. I hope that makes more sense :/

**Comment by flaura42** [comment]
FYI: When I was exploring and clicked on Settings, an error popped up that said

> Not Found
> The requested URL /templates/settings.html was not found on this server.
which would be fine if I didn't have to reload the page to get rid of it.  There wasn't an 'X' to click and hitting escape, enter, clicking off did nothing :( 

Might want to put in empty files or 'coming soon' to non-functioning/existing pages.  No biggie for this one, since it looks like you're just about ready!

**Comment by adnanusman** [comment]
@flaura42 I noticed that too, so I put in a PR with a temporary settings page.

**Comment by PepperAddict** [comment]
oh sorry about that. that was me. after the credits pr i started with settings. there was a changes requested and ended inserting that too but didnt include the file. i have a controls almost done and will correct the settings link prpblem as well. thanks for letting me know.
