### ISSUE TITLE
Error on Character selection screen

### ISSUE THREAD

**Issue by AtlantaDancer** [ignacioxd/ragin-mages#80]
I am running the DEV build on my local system.  I select multi-player.  When the character selection screen comes up I get the following error:
![characterselectionerror](https://user-images.githubusercontent.com/7062409/38067808-1e397fc6-32dc-11e8-8df4-42322126efaf.PNG)

This happens multiple times eventually it will load without errors.  I'm guessing it's a delay in actually loading characters.json into the cache or retrieving it from the cache so that we call the character creation before the data is available.

**Comment by ignacioxd** [comment]
I can't seem to replicate this on my end. Could you provide more details about your environment's state? What OS/browser are you on? Is your service worker active?

**Comment by AtlantaDancer** [comment]
I am on windows 10 using normal/stable chrome (not canary).  Yes there was a service worker going.  It may be an issue with the service worker.  Once I unchecked "enable offline" and also killed the service worker the error went away.  If I enable offline and then refresh the error occurs again.

**Comment by adnanusman** [comment]
I'm looking into this guys.

**Comment by adnanusman** [comment]
Alright here are my thoughts on the service worker, please give me your inputs and then I will refactor it accordingly.

I am thinking we don't need two caches? When the service worker loads through the enable button it basically starts off by registering a service worker, which takes it to the SW file and then it initially loads up some static files. We can set it up so it just loads up all the assets immediately then, there's no need to send a second message to the service worker since its already doing a registration and already processing files into a cache. It could be the one single file. We can still have our cache dynamically populate any files we missed using the fetchAsset function only now we'll be fetching into the one cache.

Also I was thinking to add functionality where service worker deletes any caches if it is disabled by unchecking the enable service worker box. This could be done using messaging.

**Comment by ignacioxd** [comment]
I agree that a single cache is better. When the SW is loaded it should cache all files as you say. Here's what I think should happen:

1. When the "enable service worker" box is checked, it should verify if the user is online. If the user is offline, caching cannot be enabled. This can be something we add later once we have the WebSocket portion abstracted out into a separate class.
2. If the user is online, the SW will be installed.
  2.1. Option 1: Loading of assets does not start immediately, since the SW should not fetch another copy of the `assets.json` manifest. Instead, it will receive it in a message from the game. Remember that the game has this manifest already loaded in memory.
  2.2. Option 2: The SW loads the assets.json file once more and adds things to the cache without further intervention from the game. The problem with this approach is the additional request for the manifest and having to maintain the location of the manifest in two locations: the game and the SW.
3. Once the SW has the manifest (via either option) it requests each asset/resource again to add it to the cache.

We should probably avoid dynamic caching (via fetch intercept) and instead ensure that our assets.json manifest is complete and correct. One location where we're currently dropping the ball is caching fonts and the web font loader script.

Deleting the cache when offline mode is disabled is a good idea.

**Comment by adnanusman** [comment]
Thank you for the feedback.
