### ISSUE TITLE
Player kill count stays at 0

### ISSUE THREAD

**Issue by AtlantaDancer** [ignacioxd/ragin-mages#95]
I saw mention that the player kill count is not being tallied/reported.  I have investigated this issue and I've found 2 issues that are causing this:
1. wrong ID is being sent to the client.  server\src\game\player.js line 11 should be 
```socket.emit('setId', this.id);```  (currently sending socket.id)
2. issue with client setID.  Each scene has an individual "server" listening for events.  The "setID" is received by the Title Scene server.  Thus this is the only server that has the "clientID" set and readable.  The `clientId` on the GameScene `server` is undefined.

There are several possible solutions to item 2.  Among them are (these are untested, just throwing possibilities out there - some may not actually work):
1. create method on the `server` class to return `clientId` if assigned (that also won't fail if off-line/not connected.  Pass this ID to subsequent Scenes that will assign clientID to their server.
2. have single event "Server" associated with Game object and scene "servers" subscribe to master game server emitter.
3. have scene servers subscribe to events from other servers so the ID is passed along to other  servers
4. have single "server" that is passed to scene creation and they all point to the single server.

There are probably other solutions, but these are the one I can think of right now.

What are people's thoughts?  One we have consensus I can go in and fix or someone else can.

**Comment by ignacioxd** [comment]
Thanks for investigating this with such detail. Issue (1) you identify above is indeed a bug. Instead of sending `socket.id` the server should be sending `this.id` in https://github.com/ignacioxd/ragin-mages/blob/70fabb8a3a62594a587773e1c99e1b1ce8240de8/server/src/game/Player.js#L11

Regarding issue 2, it is partially true that each scene has an individual `Server` instance, but the actual socket and the `clientID` are static members of this class and therefore shared across all scenes. See https://github.com/ignacioxd/ragin-mages/blob/70fabb8a3a62594a587773e1c99e1b1ce8240de8/game/src/js/util/Server.js#L52

In fact, the current code implements something similar to your solution (2) combined with solution (4).

I haven't tested this yet, but I think fixing issue 1 will fix this bug.
